import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation"; // Re-import Navigation with correct path
import Footer from "./components/Footer";         // Re-import Footer with correct path
import { SpeedInsights } from "@vercel/speed-insights/next"; // Re-import SpeedInsights if you want it globally

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Torres & P. PTP", // Changed to match your current code
  description: "Generated by Readdy", // Changed to match your current code
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        <Navigation /> {/* Add Navigation here */}
        <main>{children}</main> {/* Your page content */}
        <Footer />     {/* Add Footer here */}
        <SpeedInsights /> {/* Add SpeedInsights here if desired */}
      </body>
    </html>
  );
}
